apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: addon-project
  sources:
    - repoURL: https://aws.github.io/eks-charts
      targetRevision: 1.16.0
      chart: aws-load-balancer-controller
      helm:
        skipCrds: false  # ← 關鍵！讓 ArgoCD 安裝 CRD
        valueFiles:
          - $values/aws-addons/aws-load-balancer-controller/values.yaml

    - repoURL: git@github.com:tzuhsi/platform-config.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  ignoreDifferences:
    - kind: Secret
      name: aws-load-balancer-tls
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key

    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle

    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true  # 建議加上，對 CRD 更友善