apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-baseline
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
spec:
  project: default
  source:
    repoURL: git@github.com:tzuhsi/platform-config.git 
    targetRevision: main
    path: cluster-baseline
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
