apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  
spec:
  project: platform-project
  
  sources:
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 5.8.116
      helm:
        valueFiles:
          - $values/platform/jenkins/values.yaml
    - repoURL: git@github.com:tzuhsi/platform-config.git
      targetRevision: main
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true